#!/usr/bin/env python3

"""
Phase 4B: Compare threshold methods for corrected V9 attack detection.

This script does NOT redo V9 training.
This script does NOT redo Phase 3.
This script does NOT perform recovery.

It reads the corrected Phase 4 aligned attacked segments generated by:
    phase4_detect_attacks_v9_corrected.py

Then it compares three threshold strategies:

1. static_global:
   One conservative threshold per axis:
      Roll  = 0.010307
      Pitch = 0.016190
      Yaw   = 0.013596

2. scenario_specific:
   Uses the scenario/baseline-specific threshold already stored in each aligned segment:
      Threshold_p99_abs

3. dynamic_xkf1:
   For Roll/Pitch only:
      horizontal_speed = sqrt(VN^2 + VE^2)
      alpha_speed = clip((horizontal_speed - 0.5) / (2.0 - 0.5), 0, 1)
      T_axis[k] = T_hover_axis + alpha_speed[k] * (T_high_axis - T_hover_axis)

   Roll:
      T_hover = 0.006865
      T_high  = 0.010307

   Pitch:
      T_hover = 0.009161
      T_high  = 0.016190

   For Yaw:
      dynamic method falls back to conservative static global Yaw threshold:
      T_yaw = 0.013596

Window rule:
   W = 10, N = 3
   Detection if at least 3 of the last 10 samples exceed threshold.

Outputs:
   - Per-file comparison CSVs
   - Summary CSV
   - Text interpretation report
   - Comparison figures
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# Paths
# ============================================================

PROJECT_ROOT = Path("/home/tchowdh4/sensor_recovery_project")

ALIGNED_SEGMENT_DIR = PROJECT_ROOT / "attack_detection_v9_corrected" / "aligned_attacked_segments"
OUT_CSV_DIR = PROJECT_ROOT / "attack_detection_v9_corrected" / "threshold_method_comparison_csvs"
FIG_DIR = PROJECT_ROOT / "figures" / "attack_detection_v9_corrected_threshold_compare"
REPORT_DIR = PROJECT_ROOT / "detection_reports_v9_corrected"

CLEAN_DIR = PROJECT_ROOT / "logs" / "extracted_csv"

OUT_CSV_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# Threshold definitions
# ============================================================

STATIC_GLOBAL = {
    "Roll": 0.010307,
    "Pitch": 0.016190,
    "Yaw": 0.013596,
}

DYNAMIC_ROLL = {
    "T_hover": 0.006865,
    "T_high": 0.010307,
}

DYNAMIC_PITCH = {
    "T_hover": 0.009161,
    "T_high": 0.016190,
}

AXES = ["Roll", "Pitch", "Yaw"]

W = 10
N = 3


# ============================================================
# Utility functions
# ============================================================

def infer_baseline_name(text):
    baselines = [
        "baseline_01_hover",
        "baseline_02_high_altitude_hover",
        "baseline_03_forward_motion",
        "baseline_04_yaw_rotation",
        "baseline_05_mixed_maneuver",
    ]
    text = str(text)
    for b in baselines:
        if b in text:
            return b
    return None


def safe_div(num, den):
    if den == 0:
        return np.nan
    return float(num) / float(den)


def compute_metrics(y_true, y_pred):
    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)

    m = min(len(y_true), len(y_pred))
    y_true = y_true[:m]
    y_pred = y_pred[:m]

    TP = int(np.sum((y_true == 1) & (y_pred == 1)))
    FP = int(np.sum((y_true == 0) & (y_pred == 1)))
    TN = int(np.sum((y_true == 0) & (y_pred == 0)))
    FN = int(np.sum((y_true == 1) & (y_pred == 0)))

    precision = safe_div(TP, TP + FP)
    recall = safe_div(TP, TP + FN)

    if np.isfinite(precision) and np.isfinite(recall) and (precision + recall) > 0:
        f1 = 2.0 * precision * recall / (precision + recall)
    else:
        f1 = np.nan

    fpr = safe_div(FP, FP + TN)

    return {
        "TP": TP,
        "FP": FP,
        "TN": TN,
        "FN": FN,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "false_positive_rate": fpr,
    }


def compute_detection_delay(y_true, y_pred):
    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)

    attack_indices = np.where(y_true == 1)[0]

    if len(attack_indices) == 0:
        return np.nan

    attack_start = attack_indices[0]

    detection_indices = np.where(
        (np.arange(len(y_pred)) >= attack_start) & (y_pred == 1)
    )[0]

    if len(detection_indices) == 0:
        return np.nan

    return int(detection_indices[0] - attack_start)


def window_detect(abs_residual, threshold_array, W=10, N=3):
    """
    abs_residual: array
    threshold_array: scalar or array of same length

    Point exceedance:
        exceed[k] = abs_residual[k] > threshold[k]

    Window detection:
        flag[k] = 1 if sum(exceed[k-W+1:k]) >= N
    """
    abs_residual = np.asarray(abs_residual, dtype=float)

    if np.isscalar(threshold_array):
        threshold_array = np.full(len(abs_residual), float(threshold_array))
    else:
        threshold_array = np.asarray(threshold_array, dtype=float)

    m = min(len(abs_residual), len(threshold_array))
    abs_residual = abs_residual[:m]
    threshold_array = threshold_array[:m]

    exceed = (abs_residual > threshold_array).astype(int)

    window_count = (
        pd.Series(exceed)
        .rolling(window=W, min_periods=1)
        .sum()
        .to_numpy()
    )

    window_flag = (window_count >= N).astype(int)

    return exceed, window_count, window_flag, threshold_array


def find_xkf1_file(baseline):
    """
    Finds XKF1 CSV file for a baseline.
    """
    patterns = [
        f"*{baseline}*XKF1*.csv",
        f"*{baseline}*xkf1*.csv",
        f"*{baseline}*XKF*.csv",
        f"*{baseline}*xkf*.csv",
    ]

    candidates = []
    for pat in patterns:
        candidates.extend(sorted(CLEAN_DIR.rglob(pat)))

    # Remove duplicates while preserving order.
    seen = set()
    unique = []
    for p in candidates:
        if p not in seen:
            seen.add(p)
            unique.append(p)

    if not unique:
        return None

    return unique[0]


def nearest_xkf1_rows_by_time(att_timeus, xkf_df):
    """
    Returns nearest XKF1 row indices for each ATT TimeUS.
    """
    if "TimeUS" not in xkf_df.columns:
        return None

    xkf_time = pd.to_numeric(xkf_df["TimeUS"], errors="coerce").to_numpy(dtype=float)
    att_time = np.asarray(att_timeus, dtype=float)

    finite_xkf = np.isfinite(xkf_time)
    if finite_xkf.sum() < 2:
        return None

    xkf_time_valid = xkf_time[finite_xkf]
    xkf_indices_valid = np.where(finite_xkf)[0]

    order = np.argsort(xkf_time_valid)
    xkf_time_sorted = xkf_time_valid[order]
    xkf_indices_sorted = xkf_indices_valid[order]

    pos = np.searchsorted(xkf_time_sorted, att_time)

    pos_left = np.clip(pos - 1, 0, len(xkf_time_sorted) - 1)
    pos_right = np.clip(pos, 0, len(xkf_time_sorted) - 1)

    left_diff = np.abs(att_time - xkf_time_sorted[pos_left])
    right_diff = np.abs(att_time - xkf_time_sorted[pos_right])

    choose_right = right_diff < left_diff
    nearest_pos = np.where(choose_right, pos_right, pos_left)

    return xkf_indices_sorted[nearest_pos]


def get_att_timeus_for_segment(segment_df):
    """
    Reconstructs absolute ATT TimeUS for an aligned segment using:
      CleanFile
      AlignmentOffset
      length of segment

    The corrected detector aligned prediction[i] with clean ATT row offset + 1 + i.
    """
    if "CleanFile" not in segment_df.columns:
        return None

    if "AlignmentOffset" not in segment_df.columns:
        return None

    clean_file = Path(str(segment_df["CleanFile"].iloc[0]))
    offset = int(segment_df["AlignmentOffset"].iloc[0])
    n = len(segment_df)

    if not clean_file.exists():
        return None

    clean_df = pd.read_csv(clean_file)

    if "TimeUS" not in clean_df.columns:
        return None

    start = offset + 1
    end = start + n

    if end > len(clean_df):
        end = len(clean_df)

    att_time = pd.to_numeric(clean_df["TimeUS"], errors="coerce").to_numpy(dtype=float)
    att_time_segment = att_time[start:end]

    if len(att_time_segment) != n:
        m = min(len(att_time_segment), n)
        return att_time_segment[:m]

    return att_time_segment


def compute_dynamic_threshold(segment_df, axis):
    """
    Computes dynamic threshold for Roll/Pitch using XKF1 VN/VE.

    For Yaw:
        returns static global Yaw threshold array.
    """
    n = len(segment_df)
    baseline = str(segment_df["Baseline"].iloc[0]) if "Baseline" in segment_df.columns else infer_baseline_name(segment_df)

    if axis == "Yaw":
        return np.full(n, STATIC_GLOBAL["Yaw"]), "yaw_static_global", "Yaw uses conservative static global threshold"

    if axis not in ["Roll", "Pitch"]:
        return np.full(n, STATIC_GLOBAL.get(axis, np.nan)), "fallback_static_global", "Unsupported axis"

    xkf_path = find_xkf1_file(baseline)

    if xkf_path is None:
        return (
            np.full(n, STATIC_GLOBAL[axis]),
            "dynamic_xkf1_missing_fallback_static_global",
            "No XKF1 file found; used static global fallback",
        )

    xkf_df = pd.read_csv(xkf_path)

    required = ["VN", "VE"]
    missing = [c for c in required if c not in xkf_df.columns]

    if missing:
        return (
            np.full(n, STATIC_GLOBAL[axis]),
            "dynamic_xkf1_missing_columns_fallback_static_global",
            f"XKF1 file missing columns {missing}; used static global fallback",
        )

    att_timeus = get_att_timeus_for_segment(segment_df)

    if att_timeus is None:
        return (
            np.full(n, STATIC_GLOBAL[axis]),
            "dynamic_xkf1_no_time_alignment_fallback_static_global",
            "Could not reconstruct ATT TimeUS; used static global fallback",
        )

    nearest_idx = nearest_xkf1_rows_by_time(att_timeus, xkf_df)

    if nearest_idx is None:
        return (
            np.full(n, STATIC_GLOBAL[axis]),
            "dynamic_xkf1_bad_time_fallback_static_global",
            "Could not align XKF1 by TimeUS; used static global fallback",
        )

    nearest_idx = nearest_idx[:n]

    vn = pd.to_numeric(xkf_df.loc[nearest_idx, "VN"], errors="coerce").to_numpy(dtype=float)
    ve = pd.to_numeric(xkf_df.loc[nearest_idx, "VE"], errors="coerce").to_numpy(dtype=float)

    horizontal_speed = np.sqrt(vn ** 2 + ve ** 2)

    alpha_speed = np.clip(
        (horizontal_speed - 0.5) / (2.0 - 0.5),
        0.0,
        1.0,
    )

    if axis == "Roll":
        T_hover = DYNAMIC_ROLL["T_hover"]
        T_high = DYNAMIC_ROLL["T_high"]
    else:
        T_hover = DYNAMIC_PITCH["T_hover"]
        T_high = DYNAMIC_PITCH["T_high"]

    dynamic_threshold = T_hover + alpha_speed * (T_high - T_hover)

    # If any NaN appears, replace with static global as conservative fallback.
    dynamic_threshold = np.where(
        np.isfinite(dynamic_threshold),
        dynamic_threshold,
        STATIC_GLOBAL[axis],
    )

    note = f"XKF1 dynamic threshold from {xkf_path}"

    return dynamic_threshold, "dynamic_xkf1", note


def plot_threshold_comparison(
    fig_path,
    x,
    abs_residual,
    attack_active,
    flags_dict,
    thresholds_dict,
    title,
):
    """
    Creates a comparison figure:
    1. abs residual vs thresholds
    2. detection flags vs AttackActive
    """
    fig = plt.figure(figsize=(14, 8))

    ax1 = fig.add_subplot(2, 1, 1)
    ax1.plot(x, abs_residual, label="|Residual|")

    for method, T in thresholds_dict.items():
        if np.isscalar(T):
            ax1.plot(x, np.full(len(x), T), linestyle="--", label=f"{method} threshold")
        else:
            ax1.plot(x, T[:len(x)], linestyle="--", label=f"{method} threshold")

    ax1.set_ylabel("|Residual|")
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc="best")

    ax2 = fig.add_subplot(2, 1, 2)
    ax2.step(x, attack_active, where="post", label="AttackActive")

    for method, flag in flags_dict.items():
        ax2.step(x, flag[:len(x)], where="post", label=f"{method} detection", alpha=0.8)

    ax2.set_ylabel("Detection flag")
    ax2.set_xlabel("Aligned segment time/sample")
    ax2.set_ylim(-0.1, 1.2)
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc="best")

    fig.suptitle(title)
    fig.tight_layout(rect=[0, 0.03, 1, 0.95])
    fig.savefig(fig_path, dpi=160)
    plt.close(fig)


# ============================================================
# Main
# ============================================================

def main():
    segment_files = sorted(ALIGNED_SEGMENT_DIR.glob("*_aligned_attacked_segment.csv"))

    if not segment_files:
        raise FileNotFoundError(
            f"No aligned attacked segment CSV files found in {ALIGNED_SEGMENT_DIR}. "
            "Run phase4_detect_attacks_v9_corrected.py first."
        )

    print(f"[INFO] Found {len(segment_files)} aligned attacked segment files.")

    summary_rows = []

    for seg_path in segment_files:
        seg = pd.read_csv(seg_path)

        if len(seg) == 0:
            print(f"[WARN] Empty segment: {seg_path}")
            continue

        baseline = str(seg["Baseline"].iloc[0])
        axis = str(seg["Axis"].iloc[0])
        attack_type = str(seg["AttackType"].iloc[0])

        residual_col = f"Residual_{axis}"
        abs_residual_col = f"AbsResidual_{axis}"

        if abs_residual_col in seg.columns:
            abs_residual = pd.to_numeric(seg[abs_residual_col], errors="coerce").to_numpy(dtype=float)
        elif residual_col in seg.columns:
            abs_residual = np.abs(pd.to_numeric(seg[residual_col], errors="coerce").to_numpy(dtype=float))
        else:
            print(f"[WARN] Missing residual column for {seg_path}")
            continue

        attack_active = pd.to_numeric(seg["AttackActive"], errors="coerce").fillna(0).astype(int).to_numpy()

        if "x" in seg.columns:
            x = pd.to_numeric(seg["x"], errors="coerce").to_numpy(dtype=float)
            if len(x) != len(seg) or not np.isfinite(x).all():
                x = np.arange(len(seg))
        else:
            x = np.arange(len(seg))

        # Method 1: static global threshold.
        T_static_global = np.full(len(seg), STATIC_GLOBAL[axis])

        # Method 2: scenario-specific threshold.
        if "Threshold_p99_abs" in seg.columns:
            scenario_threshold_value = float(seg["Threshold_p99_abs"].iloc[0])
        else:
            scenario_threshold_value = STATIC_GLOBAL[axis]

        T_scenario = np.full(len(seg), scenario_threshold_value)

        # Method 3: XKF1 dynamic threshold for Roll/Pitch, Yaw fallback static.
        T_dynamic, dynamic_method_name, dynamic_note = compute_dynamic_threshold(seg, axis)

        methods = {
            "static_global": T_static_global,
            "scenario_specific": T_scenario,
            "dynamic_xkf1" if axis in ["Roll", "Pitch"] else "yaw_static_global": T_dynamic,
        }

        flags_for_plot = {}
        thresholds_for_plot = {}

        comparison_df = pd.DataFrame({
            "x": x,
            "Baseline": baseline,
            "Axis": axis,
            "AttackType": attack_type,
            "AttackActive": attack_active,
            "AbsResidual": abs_residual,
        })

        for method_name, T in methods.items():
            exceed, window_count, window_flag, T_array = window_detect(
                abs_residual=abs_residual,
                threshold_array=T,
                W=W,
                N=N,
            )

            comparison_df[f"Threshold_{method_name}"] = T_array
            comparison_df[f"PointExceed_{method_name}"] = exceed
            comparison_df[f"WindowCount_{method_name}"] = window_count
            comparison_df[f"WindowDetection_{method_name}"] = window_flag

            flags_for_plot[method_name] = window_flag
            thresholds_for_plot[method_name] = T_array

            metrics = compute_metrics(attack_active, window_flag)
            delay = compute_detection_delay(attack_active, window_flag)

            summary_rows.append({
                "baseline": baseline,
                "axis": axis,
                "attack_type": attack_type,
                "threshold_method": method_name,
                "dynamic_method_detail": dynamic_method_name if method_name.startswith("dynamic") or method_name.startswith("yaw") else "",
                "dynamic_note": dynamic_note if method_name.startswith("dynamic") or method_name.startswith("yaw") else "",
                "W": W,
                "N": N,
                "TP": metrics["TP"],
                "FP": metrics["FP"],
                "TN": metrics["TN"],
                "FN": metrics["FN"],
                "precision": metrics["precision"],
                "recall": metrics["recall"],
                "f1": metrics["f1"],
                "false_positive_rate": metrics["false_positive_rate"],
                "detection_delay_samples": delay,
                "n_eval_samples": len(seg),
                "input_segment_csv": str(seg_path),
            })

        out_csv = OUT_CSV_DIR / f"{baseline}_{axis}_{attack_type}_threshold_method_comparison.csv"
        comparison_df.to_csv(out_csv, index=False)

        fig_path = FIG_DIR / f"{baseline}_{axis}_{attack_type}_threshold_method_comparison.png"
        title = f"{baseline} | {axis} | {attack_type} | Threshold Method Comparison"

        plot_threshold_comparison(
            fig_path=fig_path,
            x=x,
            abs_residual=abs_residual,
            attack_active=attack_active,
            flags_dict=flags_for_plot,
            thresholds_dict=thresholds_for_plot,
            title=title,
        )

        print(f"[OK] {baseline} | {axis} | {attack_type}")

    summary = pd.DataFrame(summary_rows)

    summary_path = REPORT_DIR / "phase4b_threshold_method_comparison_v9.csv"
    summary.to_csv(summary_path, index=False)

    # Aggregate report.
    lines = []
    lines.append("PHASE 4B THRESHOLD METHOD COMPARISON REPORT")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"Input aligned segment folder: {ALIGNED_SEGMENT_DIR}")
    lines.append(f"Output comparison CSV folder: {OUT_CSV_DIR}")
    lines.append(f"Output figure folder: {FIG_DIR}")
    lines.append(f"Summary CSV: {summary_path}")
    lines.append("")
    lines.append(f"Rows in summary: {len(summary)}")
    lines.append("")

    if len(summary) > 0:
        method_summary = (
            summary.groupby("threshold_method")
            .agg(
                mean_precision=("precision", "mean"),
                mean_recall=("recall", "mean"),
                mean_f1=("f1", "mean"),
                mean_fpr=("false_positive_rate", "mean"),
                median_delay=("detection_delay_samples", "median"),
                n_rows=("threshold_method", "size"),
            )
            .reset_index()
            .sort_values(["mean_f1", "mean_fpr", "median_delay"], ascending=[False, True, True])
        )

        lines.append("Overall threshold-method comparison:")
        lines.append(method_summary.to_string(index=False))
        lines.append("")

        attack_summary = (
            summary.groupby(["threshold_method", "attack_type"])
            .agg(
                mean_precision=("precision", "mean"),
                mean_recall=("recall", "mean"),
                mean_f1=("f1", "mean"),
                mean_fpr=("false_positive_rate", "mean"),
                median_delay=("detection_delay_samples", "median"),
                n_rows=("attack_type", "size"),
            )
            .reset_index()
            .sort_values(["threshold_method", "mean_f1"], ascending=[True, False])
        )

        lines.append("Threshold method by attack type:")
        lines.append(attack_summary.to_string(index=False))
        lines.append("")

        axis_summary = (
            summary.groupby(["threshold_method", "axis"])
            .agg(
                mean_precision=("precision", "mean"),
                mean_recall=("recall", "mean"),
                mean_f1=("f1", "mean"),
                mean_fpr=("false_positive_rate", "mean"),
                median_delay=("detection_delay_samples", "median"),
                n_rows=("axis", "size"),
            )
            .reset_index()
            .sort_values(["threshold_method", "mean_f1"], ascending=[True, False])
        )

        lines.append("Threshold method by axis:")
        lines.append(axis_summary.to_string(index=False))
        lines.append("")

        best = method_summary.iloc[0]

        lines.append("Recommended threshold method:")
        lines.append(f"- {best['threshold_method']}")
        lines.append(f"- mean precision: {best['mean_precision']:.4f}")
        lines.append(f"- mean recall: {best['mean_recall']:.4f}")
        lines.append(f"- mean F1: {best['mean_f1']:.4f}")
        lines.append(f"- mean FPR: {best['mean_fpr']:.4f}")
        lines.append(f"- median detection delay: {best['median_delay']}")
        lines.append("")

        lines.append("Phase 4B decision rule:")
        lines.append("- Prefer the method with the highest mean F1.")
        lines.append("- If two methods are close, prefer lower false positive rate.")
        lines.append("- If still close, prefer lower detection delay.")
        lines.append("")

        if best["mean_recall"] >= 0.80 and best["mean_fpr"] <= 0.05:
            lines.append("Decision:")
            lines.append("- Phase 4B threshold-method comparison is acceptable.")
            lines.append("- You may carry the recommended method into Phase 5 recovery.")
        else:
            lines.append("Decision:")
            lines.append("- Phase 4B needs inspection before Phase 5.")
            if best["mean_recall"] < 0.80:
                lines.append("- Reason: best mean recall is below 0.80.")
            if best["mean_fpr"] > 0.05:
                lines.append("- Reason: best mean FPR is above 0.05.")

    report_path = REPORT_DIR / "phase4b_threshold_method_comparison_v9.txt"
    report_path.write_text("\n".join(lines))

    print()
    print("[DONE] Phase 4B threshold comparison complete.")
    print(f"[SUMMARY CSV] {summary_path}")
    print(f"[REPORT TXT]  {report_path}")
    print(f"[CSV DIR]     {OUT_CSV_DIR}")
    print(f"[FIG DIR]     {FIG_DIR}")

    if len(summary) > 0:
        print()
        print("[OVERALL METHOD SUMMARY]")
        print(method_summary.to_string(index=False))


if __name__ == "__main__":
    main()